 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/elevators", type: :request do
  # Elevator. As you add validations to Elevator, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Elevator.create! valid_attributes
      get elevators_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      elevator = Elevator.create! valid_attributes
      get elevator_url(elevator)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_elevator_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      elevator = Elevator.create! valid_attributes
      get edit_elevator_url(elevator)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Elevator" do
        expect {
          post elevators_url, params: { elevator: valid_attributes }
        }.to change(Elevator, :count).by(1)
      end

      it "redirects to the created elevator" do
        post elevators_url, params: { elevator: valid_attributes }
        expect(response).to redirect_to(elevator_url(Elevator.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Elevator" do
        expect {
          post elevators_url, params: { elevator: invalid_attributes }
        }.to change(Elevator, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post elevators_url, params: { elevator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested elevator" do
        elevator = Elevator.create! valid_attributes
        patch elevator_url(elevator), params: { elevator: new_attributes }
        elevator.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the elevator" do
        elevator = Elevator.create! valid_attributes
        patch elevator_url(elevator), params: { elevator: new_attributes }
        elevator.reload
        expect(response).to redirect_to(elevator_url(elevator))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        elevator = Elevator.create! valid_attributes
        patch elevator_url(elevator), params: { elevator: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested elevator" do
      elevator = Elevator.create! valid_attributes
      expect {
        delete elevator_url(elevator)
      }.to change(Elevator, :count).by(-1)
    end

    it "redirects to the elevators list" do
      elevator = Elevator.create! valid_attributes
      delete elevator_url(elevator)
      expect(response).to redirect_to(elevators_url)
    end
  end
end
