 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/interventions", type: :request do
  # Intervention. As you add validations to Intervention, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Intervention.create! valid_attributes
      get interventions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      intervention = Intervention.create! valid_attributes
      get intervention_url(intervention)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_intervention_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      intervention = Intervention.create! valid_attributes
      get edit_intervention_url(intervention)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Intervention" do
        expect {
          post interventions_url, params: { intervention: valid_attributes }
        }.to change(Intervention, :count).by(1)
      end

      it "redirects to the created intervention" do
        post interventions_url, params: { intervention: valid_attributes }
        expect(response).to redirect_to(intervention_url(Intervention.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Intervention" do
        expect {
          post interventions_url, params: { intervention: invalid_attributes }
        }.to change(Intervention, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post interventions_url, params: { intervention: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested intervention" do
        intervention = Intervention.create! valid_attributes
        patch intervention_url(intervention), params: { intervention: new_attributes }
        intervention.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the intervention" do
        intervention = Intervention.create! valid_attributes
        patch intervention_url(intervention), params: { intervention: new_attributes }
        intervention.reload
        expect(response).to redirect_to(intervention_url(intervention))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        intervention = Intervention.create! valid_attributes
        patch intervention_url(intervention), params: { intervention: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested intervention" do
      intervention = Intervention.create! valid_attributes
      expect {
        delete intervention_url(intervention)
      }.to change(Intervention, :count).by(-1)
    end

    it "redirects to the interventions list" do
      intervention = Intervention.create! valid_attributes
      delete intervention_url(intervention)
      expect(response).to redirect_to(interventions_url)
    end
  end
end
