default: &default
  adapter: postgresql
  database: data_warehouse
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
 adapter: postgresql
 encoding: unicode
 database: data_warehouse
 pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 username: postgres
 password: password
 host: localhost

 production:
  adapter: postgresql
  encoding: unicode
  database: data_warehouse_production
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost